name: Build Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESSTOKEN }}

    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKER_USER }}/bedrock-api-server
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        load: true
        tags: ${{ secrets.DOCKER_USER }}/bedrock-api-server:latest

    - name: Inspect
      run: |
        docker image inspect ${{ secrets.DOCKER_USER }}/bedrock-api-server:latest